/*
 * FrmAddScript.java
 *
 * Created on Jun 19, 2012, 10:28:10 PM
 */
package ilearn.scripts;

import ilearn.kernel.Utilities;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.DefaultComboBoxModel;
import org.jdesktop.application.Action;

/**
 *
 * @author mrogers
 */
public class FrmAddScript extends javax.swing.JInternalFrame
{

    /** Creates new form FrmAddScript */
    public FrmAddScript()
    {
        initComponents();
        populateLists();
    }

    private void populateLists()
    {
        ArrayList<String> list = ScriptModules.getScriptModuleList();
        list.add(0, "---Select One---");
        cmbModule.setModel(new DefaultComboBoxModel(list.toArray()));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        wrapPanel = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblModule = new javax.swing.JLabel();
        lblPriority = new javax.swing.JLabel();
        lblQauery = new javax.swing.JLabel();
        lblRemarke = new javax.swing.JLabel();
        txtTitle = new javax.swing.JTextField();
        spinnerPriority = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtQuery = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtRemarks = new javax.swing.JTextArea();
        cmdCancel = new javax.swing.JButton();
        cmdSave = new javax.swing.JButton();
        cmbModule = new javax.swing.JComboBox();
        lblSection = new javax.swing.JLabel();
        cmbSection = new javax.swing.JComboBox();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Add Script");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/ilearn/resources/script_add.png"))); // NOI18N

        wrapPanel.setName("wrapPanel"); // NOI18N

        lblTitle.setText("Title:");
        lblTitle.setName("lblTitle"); // NOI18N

        lblModule.setText("Module:");
        lblModule.setName("lblModule"); // NOI18N

        lblPriority.setText("Priority:");
        lblPriority.setName("lblPriority"); // NOI18N

        lblQauery.setText("Query:");
        lblQauery.setName("lblQauery"); // NOI18N

        lblRemarke.setText("Remarks:");
        lblRemarke.setName("lblRemarke"); // NOI18N

        txtTitle.setName("txtTitle"); // NOI18N

        spinnerPriority.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));
        spinnerPriority.setName("spinnerPriority"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        txtQuery.setColumns(20);
        txtQuery.setRows(5);
        txtQuery.setName("txtQuery"); // NOI18N
        jScrollPane1.setViewportView(txtQuery);

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        txtRemarks.setColumns(20);
        txtRemarks.setRows(5);
        txtRemarks.setName("txtRemarks"); // NOI18N
        jScrollPane2.setViewportView(txtRemarks);

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance().getContext().getActionMap(FrmAddScript.class, this);
        cmdCancel.setAction(actionMap.get("cancel")); // NOI18N
        cmdCancel.setName("cmdCancel"); // NOI18N

        cmdSave.setAction(actionMap.get("save")); // NOI18N
        cmdSave.setName("cmdSave"); // NOI18N

        cmbModule.setName("cmbModule"); // NOI18N
        cmbModule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbModuleActionPerformed(evt);
            }
        });

        lblSection.setText("Section:");
        lblSection.setName("lblSection"); // NOI18N

        cmbSection.setName("cmbSection"); // NOI18N

        javax.swing.GroupLayout wrapPanelLayout = new javax.swing.GroupLayout(wrapPanel);
        wrapPanel.setLayout(wrapPanelLayout);
        wrapPanelLayout.setHorizontalGroup(
            wrapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wrapPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(wrapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, wrapPanelLayout.createSequentialGroup()
                        .addComponent(cmdSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmdCancel))
                    .addGroup(wrapPanelLayout.createSequentialGroup()
                        .addGroup(wrapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitle)
                            .addComponent(lblPriority)
                            .addComponent(lblQauery)
                            .addComponent(lblRemarke)
                            .addComponent(lblModule)
                            .addComponent(lblSection))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(wrapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
                            .addComponent(spinnerPriority, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
                            .addComponent(txtTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
                            .addComponent(cmbSection, 0, 379, Short.MAX_VALUE)
                            .addComponent(cmbModule, 0, 379, Short.MAX_VALUE))))
                .addContainerGap())
        );
        wrapPanelLayout.setVerticalGroup(
            wrapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wrapPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(wrapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblModule)
                    .addComponent(cmbModule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(wrapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSection)
                    .addComponent(cmbSection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(wrapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitle)
                    .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(wrapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPriority)
                    .addComponent(spinnerPriority, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(wrapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblQauery)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(wrapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRemarke))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(wrapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdCancel)
                    .addComponent(cmdSave))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(wrapPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(wrapPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbModuleActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cmbModuleActionPerformed
    {
//GEN-HEADEREND:event_cmbModuleActionPerformed
        String selected = cmbModule.getSelectedItem().toString();
        if (!selected.equals("---Select One---"))
        {
            ArrayList<String> list = ScriptModules.getScriptSectionList(selected);
            list.add(0, "---Select One---");
            cmbSection.setModel(new DefaultComboBoxModel(list.toArray()));
        }
    }//GEN-LAST:event_cmbModuleActionPerformed

    @Action
    public void cancel()
    {
        Utilities.showCancelScreen(this);
    }

    @Action
    public void save()
    {
        int scriptModule = ScriptModules.findIDByModuleNameAndSection(cmbModule.getSelectedItem().toString(), cmbSection.getSelectedItem().toString());

        HashMap<String, String> params = new HashMap<String, String>();
        params.put("scriptModule", String.valueOf(scriptModule));
        params.put("scriptTitle", txtTitle.getText().trim());
        params.put("scriptQuery", txtQuery.getText().trim());
        params.put("scriptPriority", spinnerPriority.getValue().toString());
        params.put("scriptRemark", txtRemarks.getText().toString());
        boolean addScript = Scripts.addScript(params);

        if (addScript)
        {
            String message = "The script was successfully saved.";
            Utilities.showInfoMessage(rootPane, message);
        }
        else
        {
            String message = "An error occurred while trying to save this item.\n"
                    + "Kindly verify your information and try again.";
            Utilities.showWarningMessage(rootPane, message);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbModule;
    private javax.swing.JComboBox cmbSection;
    private javax.swing.JButton cmdCancel;
    private javax.swing.JButton cmdSave;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblModule;
    private javax.swing.JLabel lblPriority;
    private javax.swing.JLabel lblQauery;
    private javax.swing.JLabel lblRemarke;
    private javax.swing.JLabel lblSection;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JSpinner spinnerPriority;
    private javax.swing.JTextArea txtQuery;
    private javax.swing.JTextArea txtRemarks;
    private javax.swing.JTextField txtTitle;
    private javax.swing.JPanel wrapPanel;
    // End of variables declaration//GEN-END:variables
}
