/*
 * DialogStudentByClass.java
 *
 * Created on May 1, 2011, 1:37:20 AM
 */
package ilearn.reports;

import ilearn.grades.Grade;
import ilearn.classes.Classes;
import ilearn.kernel.Environment;
import ilearn.kernel.Utilities;
import ilearn.school.School;
import ilearn.staff.Staff;
import ilearn.subject.Subject;
import ilearn.term.Term;
import ilearn.user.User;
import java.awt.Desktop;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import org.apache.poi.hssf.usermodel.HSSFWorkbook;
import org.apache.poi.hssf.util.CellReference;
import org.apache.poi.hssf.util.HSSFColor;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellStyle;
import org.apache.poi.ss.usermodel.CreationHelper;
import org.apache.poi.ss.usermodel.DataFormat;
import org.apache.poi.ss.usermodel.Font;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.jdesktop.application.Action;
import org.jdesktop.application.Task;

/**
 *
 * @author mrogers
 */
public class FrmTeacherGradebook extends javax.swing.JInternalFrame
{
    
    File selectedFile;
    static final Logger logger = Logger.getLogger(FrmTeacherGradebook.class.getName());

    /** Creates new form DialogStudentByClass */
    public FrmTeacherGradebook()
    {
        initComponents();
        populateLists();
    }
    
    private void populateLists()
    {
        ArrayList<String> staffList = new ArrayList<String>();
        if (User.getUserGroup().equals("Administration"))
        {
            staffList = User.getPermittedStaffMembers("%");
            staffList.add(0, "--- Select One ---");
            cmbStaff.setModel(new DefaultComboBoxModel(staffList.toArray()));
        }
        else
        {
            staffList = User.getPermittedStaffMembers(User.getUserName());
            staffList.add(0, "--- Select One ---");
            cmbStaff.setModel(new DefaultComboBoxModel(staffList.toArray()));
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblStaff = new javax.swing.JLabel();
        cmbStaff = new javax.swing.JComboBox();
        cmdCancel = new javax.swing.JButton();
        cmdRun = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(FrmTeacherGradebook.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setFrameIcon(resourceMap.getIcon("Form.frameIcon")); // NOI18N
        setName("Form"); // NOI18N

        lblTitle.setFont(resourceMap.getFont("lblTitle.font")); // NOI18N
        lblTitle.setText(resourceMap.getString("lblTitle.text")); // NOI18N
        lblTitle.setName("lblTitle"); // NOI18N

        lblStaff.setText(resourceMap.getString("lblStaff.text")); // NOI18N
        lblStaff.setName("lblStaff"); // NOI18N

        cmbStaff.setName("cmbStaff"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance().getContext().getActionMap(FrmTeacherGradebook.class, this);
        cmdCancel.setAction(actionMap.get("cancel")); // NOI18N
        cmdCancel.setText(resourceMap.getString("cmdCancel.text")); // NOI18N
        cmdCancel.setName("cmdCancel"); // NOI18N

        cmdRun.setAction(actionMap.get("run")); // NOI18N
        cmdRun.setText(resourceMap.getString("cmdRun.text")); // NOI18N
        cmdRun.setName("cmdRun"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitle)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblStaff)
                        .addGap(15, 15, 15)
                        .addComponent(cmbStaff, 0, 258, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cmdRun)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmdCancel)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStaff)
                    .addComponent(cmbStaff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdCancel)
                    .addComponent(cmdRun))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @Action
    public void cancel()
    {
        this.dispose();
    }
    
    @Action(block = Task.BlockingScope.COMPONENT)
    public Task run()
    {
        return new RunTask(org.jdesktop.application.Application.getInstance(ilearn.ILearnApp.class));
    }
    
    private class RunTask extends org.jdesktop.application.Task<Object, Void>
    {
        
        File selFile;
        String staffCode;
        String classID;
        String classCode;
        String subjectCode;
        Workbook wb = new HSSFWorkbook();
        
        RunTask(org.jdesktop.application.Application app)
        {
            super(app);
            JFileChooser fc = new JFileChooser();
            fc.setFileSelectionMode(JFileChooser.FILES_ONLY);
            int returnVal = fc.showSaveDialog(rootPane);
            if (returnVal == JFileChooser.APPROVE_OPTION)
            {
                selectedFile = fc.getSelectedFile();
                try
                {
                    if (!selectedFile.getCanonicalPath().endsWith(".xls"))
                    {
                        String filename = selectedFile.getCanonicalPath();
                        filename = filename + ".xls";
                        selectedFile = new File(filename);
                    }
                }
                catch (IOException ex)
                {
                    Logger.getLogger(FrmTeacherGradebook.class.getName()).log(Level.SEVERE, null, ex);
                }
                selFile = selectedFile;
                staffCode = Staff.getStaffCodeFromName(cmbStaff.getSelectedItem().toString());
            }
            else
            {
                return;
            }
        }
        
        @Override
        protected Object doInBackground()
        {
            if (selFile == null)
            {
                return null;
            }
            
            ArrayList<HashMap> subjectList = Staff.getStaffSubjectList(staffCode);
            
            for (HashMap<String, String> subject : subjectList)
            {
                subjectCode = subject.get("subCode");
                classID = subject.get("classID");
                classCode = subject.get("classCode");
                String subID = subject.get("subID");
                if (Subject.hasWeighting(subID))
                {
                    exportWeightedSubject(subID);
                }
                else
                {
                    exportUnWeightedSubject();
                }
                
            }
            
            try
            {
                setMessage("Saving the file.");
                // Write the output to a file
                FileOutputStream fileOut = new FileOutputStream(selFile);
                wb.write(fileOut);
                fileOut.close();
                if (Desktop.isDesktopSupported())
                {
                    Desktop desktop = Desktop.getDesktop();
                    desktop.open(selFile);
                }
            }
            catch (IOException iOException)
            {
                String message = "An error occurred while generating the gradebook.\n"
                        + "Kindly check to make sure the file is not open in Excel and try again.";
                Utilities.showErrorMessage(rootPane, message);
                Logger.getLogger(FrmTeacherGradebook.class.getName()).log(Level.SEVERE, null, iOException);
            }
            return null;
        }

        /**
         * This method calculates the grade for a subject with weighting assigned to it.
         */
        private void exportWeightedSubject(String subID)
        {
            try
            {
                /**
                 * Get the passing marks and assessments
                 */
                String subCode = Subject.getSubjectCode(subID);
                double passingMark = (School.getPassingMark() / 100);
                ArrayList<String> assmtWeightType = new ArrayList<String>();
                ArrayList<Integer> assmtWeight = new ArrayList<Integer>();
                ArrayList<CellReference> cellReferences = new ArrayList<CellReference>();
                //
                //Get the assignment types and weightings.
                String sql = " SELECT `assmtType`, `weighting` FROM `Subject_Weightings`  INNER JOIN `listAssessmentTypes` ON `listAssessmentTypes`.`id` = `Subject_Weightings` .`assmentTypeID` WHERE `subID` = ? ORDER BY `weighting` DESC;";
                PreparedStatement prep = Environment.getConnection().prepareStatement(sql);
                prep.setString(1, subID);
                ResultSet rs = prep.executeQuery();
                while (rs.next())
                {
                    assmtWeightType.add(rs.getString("assmtType"));
                    assmtWeight.add(rs.getInt("weighting"));
                }
                /**
                 * Setup the workbook
                 */
                ArrayList<String> studentIDs = new ArrayList<String>();
                ArrayList<String> studentNames = new ArrayList<String>();
                Object[] stuInfo = Classes.getStudentNameList(classCode);
                studentIDs = (ArrayList<String>) stuInfo[0];
                studentNames = (ArrayList<String>) stuInfo[1];
                setMessage("Creating the workbook.");
                
                CreationHelper createHelper = wb.getCreationHelper();
                Sheet sheet = wb.createSheet(classCode + " Gradebook");
                setMessage("Creating Gradebook.");
                //Create the number format cell style
                CellStyle numberStyle = wb.createCellStyle();
                CellStyle numberStyle2 = wb.createCellStyle();
                CellStyle percentStyle = wb.createCellStyle();
                DataFormat format = wb.createDataFormat();
                numberStyle.setDataFormat(format.getFormat("#,##0.00"));
                numberStyle2.setDataFormat(format.getFormat("#,##0"));
                percentStyle.setDataFormat((short) 0xa);
                //Insert Initial info
                Row row = sheet.createRow(0);
                Cell cell = row.createCell(0);
                cell.setCellValue("Gradebook");
                row = sheet.createRow(1);
                row.createCell(0).setCellValue("Class:");
                row.createCell(1).setCellValue(classCode);
                row.createCell(3).setCellValue("Subject:");
                row.createCell(4).setCellValue(subjectCode);
                row.createCell(6).setCellValue("Term:");
                row.createCell(7).setCellValue(Term.getCurrentTermName());
                row.createCell(9).setCellValue("Teacher:");
                row.createCell(10).setCellValue(Staff.getStaffName(Subject.getSubjectTeacher(subjectCode)));
                setMessage("Inserting Data.");
                row = sheet.createRow(3);
                row.createCell(0).setCellValue(createHelper.createRichTextString("ID"));
                row.createCell(1).setCellValue(createHelper.createRichTextString("Name"));
                int startColumn = 2; //This is the column the assessments will start to print.
                int finishColumn = 2;
                int studentStartRow = 7;
                int assessmentPrinted = 0;
                Row typeRow = sheet.getRow(3);
                Row maxGradeRow = sheet.createRow(6);
                maxGradeRow.createCell(1).setCellValue("Total Points");
                Row titleRow = sheet.createRow(4);
                titleRow.createCell(1).setCellValue("Title");
                Row dateRow = sheet.createRow(5);
                dateRow.createCell(1).setCellValue("Date");
                //Print The student List.
                for (int i = 0; i < studentIDs.size(); i++)
                {
                    Row studentRow = sheet.createRow(i + studentStartRow);
                    studentRow.createCell(0).setCellValue(Integer.valueOf(studentIDs.get(i)));
                    studentRow.createCell(1).setCellValue(studentNames.get(i));
                }
                /**
                 * Print the Grades ordered by type and date.
                 */
                //Create the list objects
                ArrayList<Integer> assmtIDs = new ArrayList<Integer>();
                ArrayList<String> assmtTypes = new ArrayList<String>();
                ArrayList<String> assmtTitles = new ArrayList<String>();
                ArrayList<Date> assmtDates = new ArrayList<Date>();
                ArrayList<Integer> assmtTotalPoints = new ArrayList<Integer>();
                for (String assmtType : assmtWeightType)
                {
                    //Get the list of assessments
                    String sql1 = "SELECT `assmtID`, `assmtType`, `assmtTitle`, `assmtDate`, `assmtTotalPoints`, `assmtClassID`, `assmtSubject`, `assmtTerm`, `assmtTeacher`, `assmtStatus` FROM `Assments` WHERE `assmtClassID` = ? AND `assmtTerm` = ? AND `assmtSubject` = ? AND `assmtStatus` = 'Active' AND `assmtType` = ? ORDER BY  `assmtDate` ASC ";
                    prep = Environment.getConnection().prepareStatement(sql1);
                    prep.setString(1, classID);
                    prep.setString(2, Term.getCurrentTerm());
                    prep.setString(3, subjectCode);
                    prep.setString(4, assmtType);
                    rs = prep.executeQuery();
                    while (rs.next())
                    {
                        assmtIDs.add(rs.getInt("assmtID"));
                        assmtTypes.add(rs.getString("assmtType"));
                        assmtTitles.add(rs.getString("assmtTitle"));
                        assmtTotalPoints.add(rs.getInt("assmtTotalPoints"));
                        assmtDates.add(rs.getDate("assmtDate"));
                    }
                    rs.close();
                    prep.close();
                    //Print the assessments
                    for (int i = assessmentPrinted; i < assmtIDs.size(); i++)
                    {
                        finishColumn++;
                        typeRow.createCell(finishColumn).setCellValue(assmtIDs.get(i) + " - " + assmtTypes.get(i));
                        maxGradeRow.createCell(finishColumn).setCellValue(assmtTotalPoints.get(i));
                        titleRow.createCell(finishColumn).setCellValue(assmtTitles.get(i));
                        Cell dateCell = dateRow.createCell(finishColumn);
                        dateCell.setCellValue(new Date(assmtDates.get(i).getTime()));
                        CellStyle cellStyle = wb.createCellStyle();
                        cellStyle.setDataFormat(createHelper.createDataFormat().getFormat("MMM d, yyyy"));
                        dateCell.setCellStyle(cellStyle);
                        //for each student get their grade
                        for (int j = 7; j < (sheet.getLastRowNum() + 1); j++)
                        {
                            Row studentRow = sheet.getRow(j);
                            double stuID = studentRow.getCell(0).getNumericCellValue();
                            ArrayList<String> stuGrade = Grade.getStudentGrade(assmtIDs.get(i).toString(), String.valueOf(stuID));
                            try
                            {
                                String grade = stuGrade.get(0);
                                Cell gradeCell = studentRow.createCell(finishColumn);
                                gradeCell.setCellType(Cell.CELL_TYPE_NUMERIC);
                                try
                                {
                                    double maxPoints = Double.valueOf(assmtTotalPoints.get(i));
                                    double assmtGrade = Double.valueOf(grade);
                                    gradeCell.setCellValue(assmtGrade);
                                    if ((assmtGrade / maxPoints) < passingMark)
                                    {
                                        CellStyle style = wb.createCellStyle();
                                        Font font = wb.createFont();
                                        font.setColor(HSSFColor.RED.index);
                                        style.setFont(font);
                                        gradeCell.setCellStyle(style);
                                    }
                                }
                                catch (NumberFormatException numberFormatException)
                                {
                                    gradeCell.setCellValue(grade);
                                    if (grade.equals("Excused"))
                                    {
                                        CellStyle style = wb.createCellStyle();
                                        Font font = wb.createFont();
                                        font.setColor(HSSFColor.LIGHT_BLUE.index);
                                        style.setFont(font);
                                        studentRow.getCell(finishColumn).setCellStyle(style);
                                    }
                                    if (grade.equals("Incomplete"))
                                    {
                                        CellStyle style = wb.createCellStyle();
                                        Font font = wb.createFont();
                                        font.setColor(HSSFColor.RED.index);
                                        style.setFont(font);
                                        studentRow.getCell(finishColumn).setCellStyle(style);
                                    }
                                    if (grade.equals("Absent"))
                                    {
                                        CellStyle style = wb.createCellStyle();
                                        Font font = wb.createFont();
                                        font.setColor(HSSFColor.RED.index);
                                        style.setFont(font);
                                        studentRow.getCell(finishColumn).setCellStyle(style);
                                    }
                                }
                            }
                            catch (Exception e)
                            {
                                studentRow.createCell(finishColumn).setCellValue("Missing");
                                CellStyle style = wb.createCellStyle();
                                Font font = wb.createFont();
                                font.setColor(HSSFColor.RED.index);
                                style.setFont(font);
                                studentRow.getCell(finishColumn).setCellStyle(style);
                            }
                        }
                        assessmentPrinted++;
                    }
                    //Calculate SectionAverage
                    maxGradeRow.createCell(finishColumn + 1).setCellValue("");
                    titleRow.createCell(finishColumn + 1).setCellValue(assmtType + " Average");
                    for (int j = 7; j < (sheet.getLastRowNum() + 1); j++)
                    {
                        Row studentRow = sheet.getRow(j);
                        int stuID = (int) studentRow.getCell(0).getNumericCellValue();
                        Cell averageGradeCell = studentRow.createCell(finishColumn + 1);
                        averageGradeCell.setCellType(Cell.CELL_TYPE_NUMERIC);
                        //System.out.println(String.valueOf(stuID)+"-"+ subCode+"-"+ assmtType);
                        double assessmentTypeAverage = Grade.getAssessmentTypeAverage(String.valueOf(stuID), subCode, assmtType);
                        averageGradeCell.setCellValue(assessmentTypeAverage);
                        averageGradeCell.setCellStyle(numberStyle);
                    }
                    finishColumn += 2;
                    CellReference aveReference = new CellReference(7, finishColumn + 1);
                    cellReferences.add(aveReference);
                }
                //Calculate student averages
                titleRow = sheet.getRow(4);
                titleRow.createCell(finishColumn + 1).setCellValue("Weighted Average");
                for (int j = 6; j <= sheet.getLastRowNum(); j++)
                {
                    try
                    {
                        Row studentRow = sheet.getRow(j);
                        int stuID = (int) studentRow.getCell(0).getNumericCellValue();
                        Cell avgCell = studentRow.createCell(finishColumn + 1);
                        avgCell.setCellValue(Grade.calculateGradeWithWeighting(String.valueOf(stuID), subCode));
                        avgCell.setCellStyle(numberStyle);
                    }
                    catch (Exception e)
                    {
                    }
                }
                
            }
            catch (Exception e)
            {
                String message = "An error occurred while generating the gradebook.\n"
                        + "Kindly check to make sure the file is not open in Excel and try again.";
                Utilities.showErrorMessage(rootPane, message);
                Logger.getLogger(FrmTeacherGradebook.class.getName()).log(Level.SEVERE, null, e);
            }
        }

        /**
         * This method calculates the grades for a subject without weighting.
         */
        private void exportUnWeightedSubject()
        {
            try
            {
                //Create the list objects
                ArrayList<Integer> assmtIDs = new ArrayList<Integer>();
                ArrayList<String> assmtTypes = new ArrayList<String>();
                ArrayList<String> assmtTitles = new ArrayList<String>();
                ArrayList<Date> assmtDates = new ArrayList<Date>();
                ArrayList<Integer> assmtTotalPoints = new ArrayList<Integer>();
                ArrayList<String> studentIDs = new ArrayList<String>();
                ArrayList<String> studentNames = new ArrayList<String>();
                int passingMark = (School.getPassingMark() / 100);
                //Get the list of assessments
                String sql1 = "SELECT `assmtID`, `assmtType`, `assmtTitle`, `assmtDate`, `assmtTotalPoints`, `assmtClassID`, `assmtSubject`, `assmtTerm`, `assmtTeacher`, `assmtStatus` FROM `Assments` WHERE `assmtClassID` = ? AND `assmtTerm` = ? AND `assmtSubject` = ? AND `assmtStatus` = 'Active' ORDER BY  `assmtDate` ASC LIMIT 0, 1000;";
                PreparedStatement prep = Environment.getConnection().prepareStatement(sql1);
                prep.setString(1, classID);
                prep.setString(2, Term.getCurrentTerm());
                prep.setString(3, subjectCode);
                ResultSet rs = prep.executeQuery();
                while (rs.next())
                {
                    assmtIDs.add(rs.getInt("assmtID"));
                    assmtTypes.add(rs.getString("assmtType"));
                    assmtTitles.add(rs.getString("assmtTitle"));
                    assmtTotalPoints.add(rs.getInt("assmtTotalPoints"));
                    assmtDates.add(rs.getDate("assmtDate"));
                }
                rs.close();
                prep.close();
                Object[] stuInfo = Classes.getStudentNameList(classCode);
                studentIDs = (ArrayList<String>) stuInfo[0];
                studentNames = (ArrayList<String>) stuInfo[1];
                setMessage("Creating the workbook.");
                CreationHelper createHelper = wb.getCreationHelper();
                Sheet sheet = wb.createSheet(classCode + " Gradebook");
                setMessage("Creating Gradebook.");
                //Create the number format cell style
                CellStyle numberStyle = wb.createCellStyle();
                CellStyle numberStyle2 = wb.createCellStyle();
                CellStyle percentStyle = wb.createCellStyle();
                DataFormat format = wb.createDataFormat();
                numberStyle.setDataFormat(format.getFormat("#,##0.00"));
                numberStyle2.setDataFormat(format.getFormat("#,##0"));
                percentStyle.setDataFormat((short) 0xa);
                //Insert Initial info
                Row row = sheet.createRow(0);
                Cell cell = row.createCell(0);
                cell.setCellValue("Gradebook");
                row = sheet.createRow(1);
                row.createCell(0).setCellValue("Class:");
                row.createCell(1).setCellValue(classCode);
                row.createCell(3).setCellValue("Subject:");
                row.createCell(4).setCellValue(subjectCode);
                row.createCell(6).setCellValue("Term:");
                row.createCell(7).setCellValue(Term.getCurrentTermName());
                row.createCell(9).setCellValue("Teacher:");
                row.createCell(10).setCellValue(Staff.getStaffName(Subject.getSubjectTeacher(subjectCode)));
                setMessage("Inserting Data.");
                row = sheet.createRow(3);
                row.createCell(0).setCellValue(createHelper.createRichTextString("ID"));
                row.createCell(1).setCellValue(createHelper.createRichTextString("Name"));
                int startColumn = 2; //This is the column the assessments will start to print.
                int finishColumn = 0;
                int studentStartRow = 7;
                Row maxGradeRow = sheet.createRow(6);
                maxGradeRow.createCell(1).setCellValue("Total Points");
                Row titleRow = sheet.createRow(4);
                titleRow.createCell(1).setCellValue("Title");
                Row dateRow = sheet.createRow(5);
                dateRow.createCell(1).setCellValue("Date");
                //Print The student List.
                for (int i = 0; i < studentIDs.size(); i++)
                {
                    Row studentRow = sheet.createRow(i + studentStartRow);
                    studentRow.createCell(0).setCellValue(Integer.valueOf(studentIDs.get(i)));
                    studentRow.createCell(1).setCellValue(studentNames.get(i));
                }
                //Print the assessments
                for (int i = 0; i < assmtIDs.size(); i++)
                {
                    finishColumn = startColumn + i;
                    Row typeRow = sheet.getRow(3);
                    typeRow.createCell(startColumn + i).setCellValue(assmtIDs.get(i) + " - " + assmtTypes.get(i));
                    maxGradeRow.createCell(startColumn + i).setCellValue(assmtTotalPoints.get(i));
                    titleRow.createCell(startColumn + i).setCellValue(assmtTitles.get(i));
                    Cell dateCell = dateRow.createCell(startColumn + i);
                    dateCell.setCellValue(new Date(assmtDates.get(i).getTime()));
                    CellStyle cellStyle = wb.createCellStyle();
                    cellStyle.setDataFormat(createHelper.createDataFormat().getFormat("MMM d, yyyy"));
                    dateCell.setCellStyle(cellStyle);
                    //for each student get their grade
                    for (int j = 7; j < (sheet.getLastRowNum() + 1); j++)
                    {
                        Row studentRow = sheet.getRow(j);
                        double stuID = studentRow.getCell(0).getNumericCellValue();
                        ArrayList<String> stuGrade = Grade.getStudentGrade(assmtIDs.get(i).toString(), String.valueOf(stuID));
                        try
                        {
                            String grade = stuGrade.get(0);
                            Cell gradeCell = studentRow.createCell(startColumn + i);
                            gradeCell.setCellType(Cell.CELL_TYPE_NUMERIC);
                            try
                            {
                                double maxPoints = Double.valueOf(assmtTotalPoints.get(i));
                                double assmtGrade = Double.valueOf(grade);
                                gradeCell.setCellValue(assmtGrade);
                                if ((assmtGrade / maxPoints) < passingMark)
                                {
                                    CellStyle style = wb.createCellStyle();
                                    Font font = wb.createFont();
                                    font.setColor(HSSFColor.RED.index);
                                    style.setFont(font);
                                    studentRow.getCell(startColumn + i).setCellStyle(style);
                                }
                            }
                            catch (NumberFormatException numberFormatException)
                            {
                                gradeCell.setCellValue(grade);
                                if (grade.equals("Excused"))
                                {
                                    CellStyle style = wb.createCellStyle();
                                    Font font = wb.createFont();
                                    font.setColor(HSSFColor.LIGHT_BLUE.index);
                                    style.setFont(font);
                                    studentRow.getCell(startColumn + i).setCellStyle(style);
                                }
                                if (grade.equals("Incomplete"))
                                {
                                    CellStyle style = wb.createCellStyle();
                                    Font font = wb.createFont();
                                    font.setColor(HSSFColor.RED.index);
                                    style.setFont(font);
                                    studentRow.getCell(startColumn + i).setCellStyle(style);
                                }
                                if (grade.equals("Absent"))
                                {
                                    CellStyle style = wb.createCellStyle();
                                    Font font = wb.createFont();
                                    font.setColor(HSSFColor.RED.index);
                                    style.setFont(font);
                                    studentRow.getCell(startColumn + i).setCellStyle(style);
                                }
                            }
                        }
                        catch (Exception e)
                        {
                            studentRow.createCell(startColumn + i).setCellValue("Missing");
                            CellStyle style = wb.createCellStyle();
                            Font font = wb.createFont();
                            font.setColor(HSSFColor.RED.index);
                            style.setFont(font);
                            studentRow.getCell(startColumn + i).setCellStyle(style);
                        }
                    }
                }
                //Calculate student averages
                titleRow = sheet.getRow(4);
                titleRow.createCell(finishColumn + 1).setCellValue("Average");
                for (int j = 6; j <= sheet.getLastRowNum(); j++)
                {
                    try
                    {
                        Row studentRow = sheet.getRow(j);
                        int stuID = (int) studentRow.getCell(0).getNumericCellValue();
                        Cell avgCell = studentRow.createCell(finishColumn + 1);
                        double grade = Grade.calculateGradeWithoutWeighting(String.valueOf(stuID), subjectCode);
                        avgCell.setCellValue(grade);
                        avgCell.setCellStyle(numberStyle);
                        if (grade < passingMark * 100)
                        {
                            CellStyle style = wb.createCellStyle();
                            Font font = wb.createFont();
                            font.setColor(HSSFColor.RED.index);
                            style.setFont(font);
                            avgCell.setCellStyle(style);
                        }
                    }
                    catch (Exception e)
                    {
                    }
                }
                //calculate assessment minimum , maximum and average
                Row minRow = sheet.createRow(8 + studentIDs.size());
                Row avgRow = sheet.createRow(9 + studentIDs.size());
                Row maxRow = sheet.createRow(10 + studentIDs.size());
                Row passCountRow = sheet.createRow(11 + studentIDs.size());
                Row passPercentRow = sheet.createRow(12 + studentIDs.size());
                Row failCountRow = sheet.createRow(13 + studentIDs.size());
                Row failPercentRow = sheet.createRow(14 + studentIDs.size());
                minRow.createCell(1).setCellValue("Minimum");
                avgRow.createCell(1).setCellValue("Average");
                maxRow.createCell(1).setCellValue("Maximum");
                passCountRow.createCell(1).setCellValue("Pass Count");
                passPercentRow.createCell(1).setCellValue("Pass Percent");
                failCountRow.createCell(1).setCellValue("Fail Count");
                failPercentRow.createCell(1).setCellValue("Fail Percent");
                for (int i = 2; i <= finishColumn; i++)
                {
                    CellReference cellRefStart = new CellReference(7, i);
                    CellReference cellRefEnd = new CellReference(studentIDs.size() + 7, i);
                    Cell minCell = minRow.createCell(i);
                    minCell.setCellFormula("MIN(" + cellRefStart.formatAsString() + ":" + cellRefEnd.formatAsString() + ")");
                    minCell.setCellStyle(numberStyle);
                    Cell avgCell = avgRow.createCell(i);
                    avgCell.setCellFormula("AVERAGE(" + cellRefStart.formatAsString() + ":" + cellRefEnd.formatAsString() + ")");
                    avgCell.setCellStyle(numberStyle);
                    Cell maxCell = maxRow.createCell(i);
                    maxCell.setCellFormula("MAX(" + cellRefStart.formatAsString() + ":" + cellRefEnd.formatAsString() + ")");
                    maxCell.setCellStyle(numberStyle);
                    //Pass Info
                    int passCount = Grade.getAssessmentPassCount(assmtIDs.get(i - 2).toString());
                    Cell passCountCell = passCountRow.createCell(i);
                    passCountCell.setCellType(Cell.CELL_TYPE_NUMERIC);
                    passCountCell.setCellValue(passCount);
                    passCountCell.setCellStyle(numberStyle2);
                    //Pass Percent
                    Cell passPercentCell = passPercentRow.createCell(i);
                    //passPercentCell.setCellType(Cell.CELL_TYPE_FORMULA);
                    int classSize = studentIDs.size();
                    passPercentCell.setCellValue(Double.valueOf(passCount) / Double.valueOf(classSize));
                    passPercentCell.setCellStyle(percentStyle);
                    //Pass Info
                    int failcount = classSize - passCount;
                    Cell failcountCell = failCountRow.createCell(i);
                    failcountCell.setCellType(Cell.CELL_TYPE_NUMERIC);
                    failcountCell.setCellValue(failcount);
                    failcountCell.setCellStyle(numberStyle2);
                    //Pass Percent
                    Cell failPercentCell = failPercentRow.createCell(i);
                    //passPercentCell.setCellType(Cell.CELL_TYPE_FORMULA);
                    failPercentCell.setCellValue(Double.valueOf(failcount) / Double.valueOf(classSize));
                    failPercentCell.setCellStyle(percentStyle);
                }
//                setMessage("Saving the file.");
//                // Write the output to a file
//                FileOutputStream fileOut = new FileOutputStream(selFile);
//                wb.write(fileOut);
//                fileOut.close();
//                if (Desktop.isDesktopSupported())
//                {
//                    Desktop desktop = Desktop.getDesktop();
//                    desktop.open(selFile);
//                }
            }
            catch (Exception ex)
            {
                String message = "An error occurred while generating the gradebook.\n"
                        + "Kindly check to make sure the file is not open in Excel and try again.";
                Utilities.showErrorMessage(rootPane, message);
                Logger.getLogger(FrmTeacherGradebook.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        @Override
        protected void succeeded(Object result)
        {
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbStaff;
    private javax.swing.JButton cmdCancel;
    private javax.swing.JButton cmdRun;
    private javax.swing.JLabel lblStaff;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
