/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrmDemeritReasons.java
 *
 * Created on Dec 5, 2011, 3:34:50 PM
 */
package ilearn.school;

import ilearn.detentions.Detention;
import ilearn.kernel.TableColumnAdjuster;
import ilearn.kernel.Utilities;
import javax.swing.JOptionPane;
import org.jdesktop.application.Action;

/**
 *
 * @author m.rogers
 */
public class FrmDemeritReasons extends javax.swing.JInternalFrame
{

    /** Creates new form FrmDemeritReasons */
    public FrmDemeritReasons()
    {
        initComponents();
        populateLists();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        jScrollPane1 = new javax.swing.JScrollPane();
        demeritTable = new javax.swing.JTable();
        cmdClose = new javax.swing.JButton();
        cmdRemove = new javax.swing.JButton();
        cmdAdd = new javax.swing.JButton();
        setClosable(true);
        setIconifiable(true);
        setTitle("Manage Demerit Reasons");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/ilearn/resources/application_view_list.png"))); // NOI18N
        jScrollPane1.setName("jScrollPane1"); // NOI18N
        demeritTable.setAutoCreateRowSorter(true);
        demeritTable.setModel(new javax.swing.table.DefaultTableModel(
                                  new Object [][]
                                  {

                                  },
                                  new String []
                                  {
                                      "ID", "Description"
                                  }
                              ));
        demeritTable.setName("demeritTable"); // NOI18N
        jScrollPane1.setViewportView(demeritTable);
        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance().getContext().getActionMap(FrmDemeritReasons.class, this);
        cmdClose.setAction(actionMap.get("close")); // NOI18N
        cmdClose.setName("cmdClose"); // NOI18N
        cmdRemove.setAction(actionMap.get("delete")); // NOI18N
        cmdRemove.setName("cmdRemove"); // NOI18N
        cmdAdd.setAction(actionMap.get("Add")); // NOI18N
        cmdAdd.setName("cmdAdd"); // NOI18N
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                      .addContainerGap()
                      .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
                                .addGroup(layout.createSequentialGroup()
                                          .addComponent(cmdAdd)
                                          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                          .addComponent(cmdRemove)
                                          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                          .addComponent(cmdClose)))
                      .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                      .addContainerGap()
                      .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
                      .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                      .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cmdClose)
                                .addComponent(cmdRemove)
                                .addComponent(cmdAdd))
                      .addContainerGap())
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void populateLists()
    {
        demeritTable.setModel(DemeritReasons.getDemeritReasons());
        TableColumnAdjuster tca = new TableColumnAdjuster(demeritTable);
        tca.adjustColumns();
    }

    @Action
    public void close()
    {
        Utilities.showCancelScreen(this);
    }

    @Action
    public void delete()
    {
        if (demeritTable.getSelectedRow() != -1)
        {
            String message = "Are you sure you want to remove this item";
            int response = Utilities.showConfirmDialog(rootPane, message);
            if (response == JOptionPane.YES_OPTION)
            {
                String id = demeritTable.getValueAt(demeritTable.getSelectedRow(), 0).toString();
                DemeritReasons.deleteDemeritReason(id);
                populateLists();
            }
        }
        else
        {
            String message = "Kindly select an item to remove first.";
            Utilities.showErrorMessage(rootPane, message);
        }
    }

    @Action
    public void Add()
    {
        String name = JOptionPane.showInputDialog("Assessment Type");
        if (name.trim().isEmpty())
        {
            name = "Kindly enter a title for the entry.";
            Utilities.showWarningMessage(rootPane, name);
            return;
        }
        boolean demeritReasonAdded = DemeritReasons.addDemeritReason(name);
        if (demeritReasonAdded)
        {
            String message = "The item was successfully added.";
            Utilities.showInfoMessage(rootPane, message);
            populateLists();
        }
        else
        {
            String message = "An error occurred while trying to add a new item to the list.\n"
                             + "Kindly verify your input and try again.";
            Utilities.showErrorMessage(rootPane, message);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdAdd;
    private javax.swing.JButton cmdClose;
    private javax.swing.JButton cmdRemove;
    private javax.swing.JTable demeritTable;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
