/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrmAssessmentTypes.java
 *
 * Created on Dec 5, 2011, 2:33:43 PM
 */
package ilearn.school;

import ilearn.kernel.TableColumnAdjuster;
import ilearn.kernel.Utilities;
import javax.swing.JOptionPane;
import org.jdesktop.application.Action;

/**
 *
 * @author m.rogers
 */
public class FrmMeritReasons extends javax.swing.JInternalFrame
{

    /** Creates new form FrmAssessmentTypes */
    public FrmMeritReasons()
    {
        initComponents();
        populateLists();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        jScrollPane1 = new javax.swing.JScrollPane();
        meritReasonsTable = new javax.swing.JTable();
        cmdClose = new javax.swing.JButton();
        cmdRemove = new javax.swing.JButton();
        cmdAdd = new javax.swing.JButton();
        setClosable(true);
        setIconifiable(true);
        setTitle("Manage Merit Reasons");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/ilearn/resources/application_view_list.png"))); // NOI18N
        jScrollPane1.setName("jScrollPane1"); // NOI18N
        meritReasonsTable.setAutoCreateRowSorter(true);
        meritReasonsTable.setModel(new javax.swing.table.DefaultTableModel(
                                       new Object [][]
                                       {

                                       },
                                       new String []
                                       {
                                           "ID", "Description"
                                       }
                                   ));
        meritReasonsTable.setName("meritReasonsTable"); // NOI18N
        jScrollPane1.setViewportView(meritReasonsTable);
        meritReasonsTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance().getContext().getActionMap(FrmMeritReasons.class, this);
        cmdClose.setAction(actionMap.get("Close")); // NOI18N
        cmdClose.setName("cmdClose"); // NOI18N
        cmdRemove.setAction(actionMap.get("Delete")); // NOI18N
        cmdRemove.setName("cmdRemove"); // NOI18N
        cmdAdd.setAction(actionMap.get("Add")); // NOI18N
        cmdAdd.setName("cmdAdd"); // NOI18N
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                      .addContainerGap()
                      .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
                                .addGroup(layout.createSequentialGroup()
                                          .addComponent(cmdAdd)
                                          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                          .addComponent(cmdRemove)
                                          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                          .addComponent(cmdClose)))
                      .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                      .addContainerGap()
                      .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)
                      .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                      .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cmdClose)
                                .addComponent(cmdRemove)
                                .addComponent(cmdAdd))
                      .addContainerGap())
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void populateLists()
    {
        meritReasonsTable.setModel(MeritReasons.getMeritReasons());
        TableColumnAdjuster tca = new TableColumnAdjuster(meritReasonsTable);
        tca.adjustColumns();
    }

    @Action
    public void Close()
    {
        Utilities.showCancelScreen(this);
    }

    @Action
    public void Delete()
    {
        if (meritReasonsTable.getSelectedRow() != -1)
        {
            String message = "Are you sure you want to remove this item";
            int response = Utilities.showConfirmDialog(rootPane, message);
            if (response == JOptionPane.YES_OPTION)
            {
                String id = meritReasonsTable.getValueAt(meritReasonsTable.getSelectedRow(), 0).toString();
                MeritReasons.deleteMeritReason(id);
                populateLists();
            }
        }
        else
        {
            String message = "Kindly select an item to remove first.";
            Utilities.showErrorMessage(rootPane, message);
        }
    }

    @Action
    public void Add()
    {
        String name = JOptionPane.showInputDialog("Assessment Type");
        if (name.trim().isEmpty())
        {
            name = "Kindly enter a title for the entry.";
            Utilities.showWarningMessage(rootPane, name);
            return;
        }
        boolean meritReasonAdded = MeritReasons.addMeritReason(name);
        if (!meritReasonAdded)
        {
            String message = "An error occurred while trying to add a new item to the list.\n"
                             + "Kindly verify your input and try again.";
            Utilities.showErrorMessage(rootPane, message);
        }
        else
        {
            String message = "The item was successfully added.";
            Utilities.showInfoMessage(rootPane, message);
            populateLists();
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdAdd;
    private javax.swing.JButton cmdClose;
    private javax.swing.JButton cmdRemove;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable meritReasonsTable;
    // End of variables declaration//GEN-END:variables
}
