/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrmRegister.java
 *
 * Created on May 13, 2011, 10:44:19 AM
 */
package ilearn.register;

import ilearn.classes.Classes;
import ilearn.kernel.TableColumnAdjuster;
import ilearn.kernel.Utilities;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.application.Action;

/**
 *
 * @author m.rogers
 */
public class FrmEditRegister extends javax.swing.JInternalFrame
{

    /** Creates new form FrmRegister */
    public FrmEditRegister()
    {
        initComponents();
        populateLists();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        wrapperPanel = new javax.swing.JPanel();
        lblClass = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        calDate = new com.toedter.calendar.JDateChooser();
        cmbClass = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStudents = new javax.swing.JTable();
        cmdCancel = new javax.swing.JButton();
        cmbSave = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(ilearn.ILearnApp.class).getContext().getResourceMap(FrmEditRegister.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setFrameIcon(resourceMap.getIcon("Form.frameIcon")); // NOI18N
        setName("Form"); // NOI18N
        wrapperPanel.setName("wrapperPanel"); // NOI18N
        lblClass.setText(resourceMap.getString("lblClass.text")); // NOI18N
        lblClass.setName("lblClass"); // NOI18N
        lblDate.setText(resourceMap.getString("lblDate.text")); // NOI18N
        lblDate.setName("lblDate"); // NOI18N
        calDate.setName("calDate"); // NOI18N
        cmbClass.setName("cmbClass"); // NOI18N
        cmbClass.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cmbClassActionPerformed(evt);
            }
        });
        jScrollPane1.setName("jScrollPane1"); // NOI18N
        tblStudents.setAutoCreateRowSorter(true);
        tblStudents.setModel(new javax.swing.table.DefaultTableModel(
                                 new Object [][]
                                 {

                                 },
                                 new String []
                                 {
                                     "ID", "Name", "Present", "Demerit", "Tardy", "Remarks"
                                 }
                             )
        {
            Class[] types = new Class []
            {
                java.lang.String.class, java.lang.String.class, java.lang.Boolean.class, java.lang.Integer.class, java.lang.Boolean.class, java.lang.String.class
            };
            public Class getColumnClass(int columnIndex)
            {
                return types [columnIndex];
            }
        });
        tblStudents.setColumnSelectionAllowed(true);
        tblStudents.setName("tblStudents"); // NOI18N
        jScrollPane1.setViewportView(tblStudents);
        tblStudents.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblStudents.getColumnModel().getColumn(0).setHeaderValue(resourceMap.getString("tblStudents.columnModel.title0")); // NOI18N
        tblStudents.getColumnModel().getColumn(1).setHeaderValue(resourceMap.getString("tblStudents.columnModel.title1")); // NOI18N
        tblStudents.getColumnModel().getColumn(2).setHeaderValue(resourceMap.getString("tblStudents.columnModel.title2")); // NOI18N
        tblStudents.getColumnModel().getColumn(3).setHeaderValue(resourceMap.getString("tblStudents.columnModel.title3")); // NOI18N
        tblStudents.getColumnModel().getColumn(4).setHeaderValue(resourceMap.getString("tblStudents.columnModel.title4")); // NOI18N
        tblStudents.getColumnModel().getColumn(5).setHeaderValue(resourceMap.getString("tblStudents.columnModel.title5")); // NOI18N
        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(ilearn.ILearnApp.class).getContext().getActionMap(FrmEditRegister.class, this);
        cmdCancel.setAction(actionMap.get("cancel")); // NOI18N
        cmdCancel.setText(resourceMap.getString("cmdCancel.text")); // NOI18N
        cmdCancel.setName("cmdCancel"); // NOI18N
        cmbSave.setAction(actionMap.get("save")); // NOI18N
        cmbSave.setText(resourceMap.getString("cmbSave.text")); // NOI18N
        cmbSave.setName("cmbSave"); // NOI18N
        jButton1.setAction(actionMap.get("loadRegister")); // NOI18N
        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N
        javax.swing.GroupLayout wrapperPanelLayout = new javax.swing.GroupLayout(wrapperPanel);
        wrapperPanel.setLayout(wrapperPanelLayout);
        wrapperPanelLayout.setHorizontalGroup(
            wrapperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wrapperPanelLayout.createSequentialGroup()
                      .addContainerGap()
                      .addGroup(wrapperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 495, Short.MAX_VALUE)
                                .addGroup(wrapperPanelLayout.createSequentialGroup()
                                          .addComponent(cmbSave)
                                          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                          .addComponent(cmdCancel))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, wrapperPanelLayout.createSequentialGroup()
                                          .addGroup(wrapperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                  .addComponent(lblDate)
                                                  .addComponent(lblClass))
                                          .addGap(3, 3, 3)
                                          .addGroup(wrapperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                  .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, wrapperPanelLayout.createSequentialGroup()
                                                          .addComponent(cmbClass, 0, 336, Short.MAX_VALUE)
                                                          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                          .addComponent(jButton1))
                                                  .addComponent(calDate, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE))))
                      .addContainerGap())
        );
        wrapperPanelLayout.setVerticalGroup(
            wrapperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wrapperPanelLayout.createSequentialGroup()
                      .addContainerGap()
                      .addGroup(wrapperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                .addComponent(calDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblDate))
                      .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                      .addGroup(wrapperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblClass)
                                .addComponent(cmbClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton1))
                      .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                      .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                      .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                      .addGroup(wrapperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cmdCancel)
                                .addComponent(cmbSave))
                      .addContainerGap())
        );
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(wrapperPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(wrapperPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbClassActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cmbClassActionPerformed
    {
//GEN-HEADEREND:event_cmbClassActionPerformed
//        if (!cmbClass.getSelectedItem().toString().equals("--- Select One ---"))
//        {
//            loadStudentList();
//        }
    }//GEN-LAST:event_cmbClassActionPerformed

    @Action
    public void cancel()
    {
        Utilities.showCancelScreen(this);
        populateLists();
    }

    @Action
    public void save()
    {
        String date = Utilities.YMD_Formatter.format(calDate.getDate());
        String clsCode = cmbClass.getSelectedItem().toString();
        ArrayList<String> stuID = new ArrayList<String>();
        ArrayList<Boolean> absent = new ArrayList<Boolean>();
        ArrayList<Integer> demerit = new ArrayList<Integer>();
        ArrayList<Boolean> tardy = new ArrayList<Boolean>();
        ArrayList<String> remarks = new ArrayList<String>();
        for (int i = 0; i < tblStudents.getRowCount(); i++)
        {
            String stuid = tblStudents.getValueAt(i, 0).toString();
            boolean Absent = (Boolean) tblStudents.getValueAt(i, 2);
            int Demerit = (Integer) tblStudents.getValueAt(i, 3);
            boolean Tardy = (Boolean) tblStudents.getValueAt(i, 4);
            String Remark = tblStudents.getValueAt(i, 5).toString();
            if (Absent == true || Demerit > 0 || Tardy == true)
            {
                stuID.add(stuid);
                absent.add(Absent);
                demerit.add(Demerit);
                tardy.add(Tardy);
                remarks.add(Remark);
            }
        }
        boolean wipeRegister = Register.wipeRegister(clsCode, date);
        boolean addRegister = Register.addRegister(date, stuID, absent, demerit, tardy, remarks, clsCode);
        if (wipeRegister && addRegister)
        {
            String message = "The register was successfully updated. \n"
                             + "Would you like to edit another?";
            int response = Utilities.showConfirmDialog(rootPane, message);
            if (response == JOptionPane.YES_OPTION)
            {
                resetForm();
            }
            else
            {
                this.dispose();
            }
        }
        else
        {
            String message = "An error occurred while trying to save this assessment.\n"
                             + "Kindly verify your information and try again.";
            Utilities.showErrorMessage(rootPane, message);
        }
    }

    private void populateLists()
    {
        calDate.setDate(new Date());
        ArrayList<String> clsList = Classes.getClassList();
        clsList.add(0, "--- Select One ---");
        cmbClass.setModel(new DefaultComboBoxModel(clsList.toArray()));
    }

    private void loadStudentList()
    {
        if (!cmbClass.getSelectedItem().toString().equals("--- Select One ---"))
        {
            DefaultTableModel model = Register.getStudentList(cmbClass.getSelectedItem().toString());
            tblStudents.setModel(model);
            TableColumnAdjuster tca = new TableColumnAdjuster(tblStudents);
            tca.adjustColumns();
        }
        else
        {
            String message = "Kindly select a class first.";
            Utilities.showWarningMessage(rootPane, message);
        }
    }

    private void resetForm()
    {
        remove(wrapperPanel);
        initComponents();
        populateLists();
    }

    @Action
    public void loadRegister()
    {
        loadStudentList();
        String clsCode = cmbClass.getSelectedItem().toString();
        String date = Utilities.YMD_Formatter.format(calDate.getDate());
        ArrayList<Object> register = Register.getClassRegister(clsCode, date);
        ArrayList<String> stuID = (ArrayList<String>) register.get(0);
        ArrayList<Boolean> absent = (ArrayList<Boolean>) register.get(1);
        ArrayList<Boolean> tardy = (ArrayList<Boolean>) register.get(2);
        ArrayList<Integer> demerit = (ArrayList<Integer>) register.get(3);
        ArrayList<String> remark = (ArrayList<String>) register.get(4);
        for (int i = 0; i < stuID.size(); i++)
        {
            String currID = stuID.get(i);
            for (int j = 0; j < tblStudents.getRowCount(); j++)
            {
                String tblID = tblStudents.getValueAt(j, 0).toString();
                if (currID.equals(tblID))
                {
                    tblStudents.setValueAt(absent.get(i), j, 2);
                    tblStudents.setValueAt(demerit.get(i), j, 3);
                    tblStudents.setValueAt(tardy.get(i), j, 4);
                    tblStudents.setValueAt(remark.get(i), j, 5);
                }
            }
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser calDate;
    private javax.swing.JComboBox cmbClass;
    private javax.swing.JButton cmbSave;
    private javax.swing.JButton cmdCancel;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblClass;
    private javax.swing.JLabel lblDate;
    private javax.swing.JTable tblStudents;
    private javax.swing.JPanel wrapperPanel;
    // End of variables declaration//GEN-END:variables
}
